- name: Update nginx master vhost
  tags: run
  template: src=nginx.production.j2 dest=/etc/nginx/sites-enabled/{{ app_name }}
  notify: reload nginx

- name: Update DNS master record
  dnsmadeeasy: >
    account_key={{ dnsmadeeasy_key }}
    account_secret={{ dnsmadeeasy_secret }}
    domain={{ app_fqdn }}
    state=present
    record_type=A
    record_value={{ ansible_default_ipv4.address }}

- name: Notify HipChat of new master container
  hipchat: >
    token={{ hipchat_token }}
    room={{ hipchat_room }}
    from={{ hipchat_from }}
    msg="Latest {{ app_name }}/master shipped: {{ app_http_scheme }}://{{ app_fqdn }}"
    color=green
