---
- name: DigitalOcean
  hosts: localhost

  vars_files:
    - vars/digital_ocean.yml

  tasks:
  - name: Delete DigitalOcean Droplet
    digital_ocean: >
      state=deleted
      name={{ name }}
      unique_name=yes
      region_id={{ region_id }}
      size_id={{ size_id }}
      region_id={{ region_id }}
      image_id={{ image_id }}
